### ISSUE TITLE
a rectangle at the top left corner of top panel

### ISSUE THREAD

**Issue by Sadi58** [psifidotos/paneltransparencybutton#1]
I tried to use this widget with the latest Feren OS, but experienced this issue as can be seen in the screenshot below.
![Screenshot_20200118_191442](https://user-images.githubusercontent.com/6375934/72666946-c2873d80-3a27-11ea-9750-e8036c5ecbbc.png)
Additionally, I think this very attractive widget would be much better if transparency level could be adjusted or at least another small tweak like changing the color of all items in the panel in contrast to the background or adding a little shadow maybe?

**Comment by psifidotos** [comment]
> I tried to use this widget with the latest Feren OS, but experienced this issue as can be seen in the screenshot below.

what issue?

> Additionally, I think this very attractive widget would be much better if transparency level could be adjusted or at least another small tweak like changing the color of all items in the panel in contrast to the background or adding a little shadow maybe?

this is plasma panel responsibility, nothing to do with this applet... All these features you want are already provided from Latte panels and Latte is already preinstalled in FerenOS

**Comment by Sadi58** [comment]
The issue was specified in the heading and showed in the screenshot: a rectangle at the top left corner. However, after some trial-and-error, I've found out that as a new returnee to KDE after many years I have somehow made a mess of my plasma settings, and resetting it all got rid of that strange dock/panel residue.
Thanks for the tip about latte-dock!
