### ISSUE TITLE
Please add active transparency

### ISSUE THREAD

**Issue by RezaSh13** [psifidotos/paneltransparencybutton#2]
I mean when the window is minimized the transparency be enable like this picture
![image](https://user-images.githubusercontent.com/22277992/74517956-51548080-4f28-11ea-94a2-182d81a2eceb.png)

and when the window is maximized the transparency be enable like this picture
![image](https://user-images.githubusercontent.com/22277992/74518574-5665ff80-4f29-11ea-8d09-9904a663653c.png)

**Comment by psifidotos** [comment]
Why don't you just use a Latte panel which is more sophisticated?

**Comment by RezaSh13** [comment]
> Why don't you just use a Latte panel which is more sophisticated?

It's little buggy :)

**Comment by psifidotos** [comment]
> > Why don't you just use a Latte panel which is more sophisticated?
> 
> It's little buggy :)

Tell me some of the bugs or provide me with their links

**Comment by psifidotos** [comment]
you can now use Plasma 5.22 adaptive transparency
